import type { AnomalyRule } from "./types";

/**
 * 10 heuristische Regeln. Schwellen sind anpassbar im Admin-UI.
 */
export const defaultRules: AnomalyRule[] = [
  {
    kind: "bulk-delete",
    label: "Massenhaftes Löschen",
    description: ">= N Delete-Events eines Users innerhalb eines Zeitfensters.",
    enabled: true,
    threshold: 50,
    windowMs: 5 * 60_000,
    severity: "high",
  },
  {
    kind: "off-hours-export",
    label: "Export außerhalb der Kernzeit",
    description: "Datenexport zwischen 22:00 und 06:00.",
    enabled: true,
    threshold: 1,
    windowMs: 60_000,
    severity: "high",
  },
  {
    kind: "role-escalation",
    label: "Rollen-Eskalation",
    description: "User-Rollen-Änderung auf admin/pdl.",
    enabled: true,
    threshold: 1,
    windowMs: 60_000,
    severity: "critical",
  },
  {
    kind: "geo-unusual",
    label: "Ungewöhnliches Land",
    description: "Login aus Land, das nicht im typischen Baseline-Set des Users ist.",
    enabled: true,
    threshold: 1,
    windowMs: 60_000,
    severity: "medium",
  },
  {
    kind: "rapid-access",
    label: "Schneller Serienzugriff",
    description: ">= N Read-Events auf Bewohnerakten in kurzer Zeit.",
    enabled: true,
    threshold: 100,
    windowMs: 5 * 60_000,
    severity: "medium",
  },
  {
    kind: "credential-stuffing",
    label: "Credential Stuffing",
    description: ">= N fehlgeschlagene Logins pro IP in kurzer Zeit.",
    enabled: true,
    threshold: 10,
    windowMs: 5 * 60_000,
    severity: "high",
  },
  {
    kind: "data-spike",
    label: "Aktivitäts-Spike (Z-Score)",
    description: "Tägliche Aktivität eines Users liegt > 3 Standardabweichungen über Baseline.",
    enabled: true,
    threshold: 3,
    windowMs: 24 * 3600_000,
    severity: "medium",
  },
  {
    kind: "permission-overuse",
    label: "Permission-Übernutzung",
    description: "User greift in kurzer Zeit auf ungewöhnlich viele verschiedene Entities zu.",
    enabled: true,
    threshold: 200,
    windowMs: 60 * 60_000,
    severity: "medium",
  },
  {
    kind: "dormant-reactivation",
    label: "Wiederaktivierung ruhendes Konto",
    description: "Login auf Konto nach >30 Tagen Inaktivität.",
    enabled: true,
    threshold: 30,
    windowMs: 24 * 3600_000,
    severity: "low",
  },
  {
    kind: "after-hours-login",
    label: "Login außerhalb typischer Zeiten",
    description: "Login zu einer Stunde, die außerhalb der typischen Stunden des Users liegt.",
    enabled: true,
    threshold: 1,
    windowMs: 60_000,
    severity: "low",
  },
];
