import type { FeatureFlag } from "./types";

const now = Date.now();

export function seedFlags(): FeatureFlag[] {
  return [
    {
      key: "voice-realtime-transcription",
      name: "Realtime Voice Transcription",
      description: "Live-Transkription während der Spracheingabe statt Batch-Upload.",
      kind: "boolean",
      enabled: true,
      defaultValue: false,
      rules: [
        { id: "r1", description: "Admins + PDL erhalten Preview", enabled: true, roles: ["admin", "pdl"] },
        { id: "r2", description: "20 % Rollout Pflegekräfte", enabled: true, roles: ["pflegekraft"], rolloutPercent: 20 },
      ],
      owner: "Product",
      tags: ["voice", "preview"],
      createdAt: now - 30 * 86_400_000,
      updatedAt: now - 2 * 86_400_000,
    },
    {
      key: "ai-handover-v2",
      name: "Schichtübergabe KI-Assistent v2",
      description: "Neue LLM-gestützte Handover-Zusammenfassung (GPT-4o).",
      kind: "boolean",
      enabled: true,
      defaultValue: false,
      rules: [{ id: "r1", description: "50 % Rollout Tenant Hietzing", enabled: true, tenantIds: ["tenant-demo"], rolloutPercent: 50 }],
      owner: "AI",
      tags: ["ai", "rollout"],
      createdAt: now - 14 * 86_400_000,
      updatedAt: now - 86_400_000,
    },
    {
      key: "telemed-enabled",
      name: "Telemedizin-Modul",
      description: "Aktiviert die Video-Sprechstunde.",
      kind: "boolean",
      enabled: true,
      defaultValue: true,
      rules: [],
      owner: "Product",
      tags: ["module"],
      createdAt: now - 60 * 86_400_000,
      updatedAt: now - 5 * 86_400_000,
    },
    {
      key: "knowledge-graph",
      name: "Medizinischer Knowledge-Graph",
      description: "Verknüpft Diagnosen, Medikamente, Bewohner:innen.",
      kind: "boolean",
      enabled: true,
      defaultValue: false,
      rules: [{ id: "r1", description: "Enterprise-Tenants", enabled: true, tenantIds: ["tenant-demo"] }],
      owner: "AI",
      tags: ["ai"],
      createdAt: now - 20 * 86_400_000,
      updatedAt: now - 3 * 86_400_000,
    },
    {
      key: "new-dashboard",
      name: "Admin-Dashboard v3",
      description: "Neue Dashboard-UI mit Widgets & Drag'n'Drop.",
      kind: "boolean",
      enabled: true,
      defaultValue: false,
      rules: [{ id: "r1", description: "30 % Admins", enabled: true, roles: ["admin"], rolloutPercent: 30 }],
      owner: "Design",
      tags: ["ui", "experiment"],
      createdAt: now - 10 * 86_400_000,
      updatedAt: now - 86_400_000,
    },
    {
      key: "mdk-auto-export",
      name: "MDK Auto-Export",
      description: "Automatischer MDK-Export jeden 1. des Monats.",
      kind: "boolean",
      enabled: false,
      defaultValue: false,
      rules: [],
      owner: "Compliance",
      tags: ["compliance"],
      createdAt: now - 40 * 86_400_000,
      updatedAt: now - 15 * 86_400_000,
    },
    {
      key: "wearable-integration",
      name: "Wearable-Integration",
      description: "Apple Watch / Fitbit Vitalwerte einlesen.",
      kind: "boolean",
      enabled: true,
      defaultValue: false,
      rules: [{ id: "r1", description: "Beta-Tester (E-Mail)", enabled: true, emailContains: "beta" }],
      owner: "Product",
      tags: ["beta"],
      createdAt: now - 25 * 86_400_000,
      updatedAt: now - 4 * 86_400_000,
    },
    {
      key: "family-chat-emoji-reactions",
      name: "Emoji-Reaktionen Familien-Chat",
      description: "Angehörige können auf Nachrichten mit Emojis reagieren.",
      kind: "boolean",
      enabled: true,
      defaultValue: true,
      rules: [],
      owner: "Design",
      tags: ["family"],
      createdAt: now - 7 * 86_400_000,
      updatedAt: now - 86_400_000,
    },
    {
      key: "billing-self-service",
      name: "Billing Self-Service",
      description: "Kunden können Pläne selbst up/downgraden.",
      kind: "boolean",
      enabled: true,
      defaultValue: false,
      rules: [{ id: "r1", description: "Nur Admin", enabled: true, roles: ["admin"] }],
      owner: "Billing",
      tags: ["billing"],
      createdAt: now - 12 * 86_400_000,
      updatedAt: now - 86_400_000,
    },
    {
      key: "zeiterfassung-geofence",
      name: "Zeiterfassung Geofence",
      description: "Stempeln nur am Standort der Einrichtung möglich.",
      kind: "boolean",
      enabled: false,
      defaultValue: false,
      rules: [],
      owner: "HR",
      tags: ["hr", "compliance"],
      createdAt: now - 5 * 86_400_000,
      updatedAt: now - 86_400_000,
    },
    {
      key: "handover-sms-notify",
      name: "SMS-Benachrichtigung Schichtübergabe",
      description: "SMS statt Push bei kritischen Übergaben.",
      kind: "boolean",
      enabled: true,
      defaultValue: false,
      rules: [{ id: "r1", description: "PDL erhalten SMS", enabled: true, roles: ["pdl"] }],
      owner: "Operations",
      tags: ["notification"],
      createdAt: now - 9 * 86_400_000,
      updatedAt: now - 2 * 86_400_000,
    },
    {
      key: "dark-mode-default",
      name: "Dark Mode als Default",
      description: "Neue User starten im Dark Mode.",
      kind: "boolean",
      enabled: true,
      defaultValue: false,
      rules: [{ id: "r1", description: "50 % Rollout", enabled: true, rolloutPercent: 50 }],
      owner: "Design",
      tags: ["ui", "experiment"],
      createdAt: now - 3 * 86_400_000,
      updatedAt: now - 86_400_000,
    },
    {
      key: "onboarding-tour-v2",
      name: "Onboarding-Tour v2",
      description: "A/B: neue vs. alte Onboarding-Tour.",
      kind: "multivariate",
      enabled: true,
      defaultValue: "v1",
      variants: ["v1", "v2"],
      rules: [
        { id: "r1", description: "50 % erhalten v2", enabled: true, rolloutPercent: 50, variant: "v2" },
      ],
      owner: "Growth",
      tags: ["experiment", "ab-test"],
      createdAt: now - 6 * 86_400_000,
      updatedAt: now - 86_400_000,
    },
    {
      key: "report-pdf-compression",
      name: "PDF-Kompression für Reports",
      description: "Reduziert Report-Größe um ~60 %.",
      kind: "boolean",
      enabled: true,
      defaultValue: true,
      rules: [],
      owner: "Platform",
      tags: ["performance"],
      createdAt: now - 45 * 86_400_000,
      updatedAt: now - 20 * 86_400_000,
    },
    {
      key: "audit-realtime-stream",
      name: "Audit-Log Realtime-Stream",
      description: "WebSocket-Stream für Audit-Events (statt Polling).",
      kind: "boolean",
      enabled: false,
      defaultValue: false,
      rules: [],
      owner: "Security",
      tags: ["security", "performance"],
      createdAt: now - 2 * 86_400_000,
      updatedAt: now - 86_400_000,
    },
    {
      key: "impersonation-enabled",
      name: "Impersonation Support-Tool",
      description: "Admins dürfen sich als User einloggen (Support).",
      kind: "boolean",
      enabled: true,
      defaultValue: false,
      rules: [{ id: "r1", description: "Nur Admin-Rolle", enabled: true, roles: ["admin"] }],
      owner: "Support",
      tags: ["support", "security"],
      createdAt: now - 8 * 86_400_000,
      updatedAt: now - 86_400_000,
    },
    {
      key: "ai-medikation-check",
      name: "KI-Medikations-Wechselwirkungs-Check",
      description: "Automatische Prüfung bei jeder Medikationsänderung.",
      kind: "boolean",
      enabled: true,
      defaultValue: false,
      rules: [{ id: "r1", description: "25 % Pro/Enterprise", enabled: true, rolloutPercent: 25 }],
      owner: "AI",
      tags: ["ai", "safety"],
      createdAt: now - 4 * 86_400_000,
      updatedAt: now - 86_400_000,
    },
    {
      key: "offline-mode",
      name: "Offline-Modus",
      description: "App funktioniert offline, synced später.",
      kind: "boolean",
      enabled: false,
      defaultValue: false,
      rules: [],
      owner: "Mobile",
      tags: ["mobile", "beta"],
      createdAt: now - 15 * 86_400_000,
      updatedAt: now - 10 * 86_400_000,
    },
    {
      key: "invoice-payment-integration",
      name: "Rechnungs-Payment (Stripe)",
      description: "Direkt aus der Invoice bezahlen.",
      kind: "boolean",
      enabled: true,
      defaultValue: false,
      rules: [{ id: "r1", description: "Enterprise", enabled: true, tenantIds: ["tenant-demo"] }],
      owner: "Billing",
      tags: ["billing"],
      createdAt: now - 11 * 86_400_000,
      updatedAt: now - 86_400_000,
    },
    {
      key: "new-resident-form",
      name: "Bewohner-Formular v2",
      description: "Mehrspaltiges Layout, schnelleres Anlegen.",
      kind: "boolean",
      enabled: true,
      defaultValue: true,
      rules: [],
      owner: "Design",
      tags: ["ui"],
      createdAt: now - 50 * 86_400_000,
      updatedAt: now - 30 * 86_400_000,
    },
  ];
}
