/**
 * Katalog aller verfuegbaren Badges (40+).
 *
 * Struktur: Qualifikationen (DGKP, PFA, ...), Expertise (Wundexpert:in ICW, ...),
 * Weiterbildung (Hygienebeauftragte:r, ...), Zertifikate (BLS-AED, ...),
 * Rollen (Schichtleitung, PDL, ...).
 */

import type { BadgeDef } from "./types";

export const BADGE_CATALOG: BadgeDef[] = [
  // Qualifikationen
  {
    key: "dgkp",
    name: "DGKP — Diplomierte:r Gesundheits- und Krankenpfleger:in",
    category: "qualifikation",
    level: "expert",
    description: "Gehobener Dienst in der Gesundheits- und Krankenpflege.",
    validityMonths: null,
    requiresProof: true,
    fromLms: false,
    iconKey: "GraduationCap",
    color: "text-sky-700 bg-sky-50 border-sky-200",
  },
  {
    key: "pfa",
    name: "PFA — Pflegefachassistenz",
    category: "qualifikation",
    level: "erweitert",
    description: "Pflegefachassistenz-Ausbildung.",
    validityMonths: null,
    requiresProof: true,
    fromLms: false,
    iconKey: "GraduationCap",
    color: "text-sky-700 bg-sky-50 border-sky-200",
  },
  {
    key: "heimhilfe",
    name: "Heimhilfe",
    category: "qualifikation",
    level: "basis",
    description: "Heimhilfe-Ausbildung.",
    validityMonths: null,
    requiresProof: true,
    fromLms: false,
    iconKey: "GraduationCap",
    color: "text-sky-700 bg-sky-50 border-sky-200",
  },
  {
    key: "zivildiener",
    name: "Zivildiener",
    category: "qualifikation",
    level: "basis",
    description: "Ableistung Zivildienst.",
    validityMonths: 12,
    requiresProof: false,
    fromLms: false,
    iconKey: "Shield",
    color: "text-gray-700 bg-gray-50 border-gray-200",
  },
  {
    key: "praktikant",
    name: "Pflegepraktikant:in",
    category: "qualifikation",
    level: "basis",
    description: "In Ausbildung befindlich.",
    validityMonths: 12,
    requiresProof: false,
    fromLms: false,
    iconKey: "BookOpen",
    color: "text-gray-700 bg-gray-50 border-gray-200",
  },
  {
    key: "fsj",
    name: "Freiwilliges Soziales Jahr",
    category: "qualifikation",
    level: "basis",
    description: "FSJ in der Einrichtung.",
    validityMonths: 12,
    requiresProof: false,
    fromLms: false,
    iconKey: "HeartHandshake",
    color: "text-gray-700 bg-gray-50 border-gray-200",
  },
  // Expertise
  {
    key: "wundexpert_icw",
    name: "Wundexpert:in ICW",
    category: "expertise",
    level: "expert",
    description: "Zertifizierte:r Wundexpert:in nach ICW-Curriculum.",
    validityMonths: 24,
    requiresProof: true,
    fromLms: false,
    iconKey: "Bandage",
    color: "text-rose-700 bg-rose-50 border-rose-200",
  },
  {
    key: "pain_nurse",
    name: "Pain Nurse",
    category: "expertise",
    level: "expert",
    description: "Schmerzmanagement-Expert:in.",
    validityMonths: 36,
    requiresProof: true,
    fromLms: false,
    iconKey: "Activity",
    color: "text-rose-700 bg-rose-50 border-rose-200",
  },
  {
    key: "demenz_beauftragt",
    name: "Demenz-Beauftragte:r",
    category: "expertise",
    level: "erweitert",
    description: "Fachkraft fuer Demenzbetreuung.",
    validityMonths: null,
    requiresProof: true,
    fromLms: false,
    iconKey: "Brain",
    color: "text-purple-700 bg-purple-50 border-purple-200",
  },
  {
    key: "palliativ_fk",
    name: "Palliativ-Fachkraft",
    category: "expertise",
    level: "expert",
    description: "Palliativ- und Hospizbetreuung.",
    validityMonths: null,
    requiresProof: true,
    fromLms: false,
    iconKey: "Heart",
    color: "text-pink-700 bg-pink-50 border-pink-200",
  },
  {
    key: "onko_pflege",
    name: "Onkologische Pflege",
    category: "expertise",
    level: "erweitert",
    description: "Weiterbildung onkologische Pflege.",
    validityMonths: null,
    requiresProof: true,
    fromLms: false,
    iconKey: "Dna",
    color: "text-rose-700 bg-rose-50 border-rose-200",
  },
  {
    key: "stoma_pflege",
    name: "Stoma-Pflege",
    category: "expertise",
    level: "erweitert",
    description: "Stoma-Fachpflege.",
    validityMonths: null,
    requiresProof: true,
    fromLms: false,
    iconKey: "Circle",
    color: "text-amber-700 bg-amber-50 border-amber-200",
  },
  {
    key: "wundmanager",
    name: "Wundmanager:in",
    category: "expertise",
    level: "expert",
    description: "Strukturiertes Wundmanagement.",
    validityMonths: 24,
    requiresProof: true,
    fromLms: false,
    iconKey: "Bandage",
    color: "text-rose-700 bg-rose-50 border-rose-200",
  },
  // Weiterbildung
  {
    key: "hygiene_beauftragt",
    name: "Hygienebeauftragte:r",
    category: "weiterbildung",
    level: "erweitert",
    description: "Hygieneweiterbildung.",
    validityMonths: 24,
    requiresProof: true,
    fromLms: false,
    iconKey: "Sparkles",
    color: "text-teal-700 bg-teal-50 border-teal-200",
  },
  {
    key: "sturz_beauftragt",
    name: "Sturzbeauftragte:r",
    category: "weiterbildung",
    level: "erweitert",
    description: "Sturzprophylaxe-Expert:in.",
    validityMonths: 24,
    requiresProof: true,
    fromLms: false,
    iconKey: "ShieldAlert",
    color: "text-amber-700 bg-amber-50 border-amber-200",
  },
  {
    key: "arzneimittel_beauftragt",
    name: "Arzneimittel-Beauftragte:r",
    category: "weiterbildung",
    level: "erweitert",
    description: "Medikationssicherheit.",
    validityMonths: 24,
    requiresProof: true,
    fromLms: false,
    iconKey: "Pill",
    color: "text-indigo-700 bg-indigo-50 border-indigo-200",
  },
  {
    key: "qm_beauftragt",
    name: "Qualitaetsbeauftragte:r",
    category: "weiterbildung",
    level: "expert",
    description: "Qualitaetsmanagement nach ISO/Pflege.",
    validityMonths: null,
    requiresProof: true,
    fromLms: false,
    iconKey: "BadgeCheck",
    color: "text-emerald-700 bg-emerald-50 border-emerald-200",
  },
  {
    key: "ethikberater",
    name: "Ethikberater:in",
    category: "weiterbildung",
    level: "expert",
    description: "Ethische Fallbesprechung.",
    validityMonths: null,
    requiresProof: true,
    fromLms: false,
    iconKey: "Scale",
    color: "text-purple-700 bg-purple-50 border-purple-200",
  },
  {
    key: "kinaesthetik",
    name: "Kinaesthetik-Trainer:in",
    category: "weiterbildung",
    level: "erweitert",
    description: "Bewegungsunterstuetzung.",
    validityMonths: null,
    requiresProof: true,
    fromLms: false,
    iconKey: "Move",
    color: "text-teal-700 bg-teal-50 border-teal-200",
  },
  {
    key: "basale_stimulation",
    name: "Basale Stimulation",
    category: "weiterbildung",
    level: "erweitert",
    description: "Foerderkonzept fuer Wahrnehmung und Kommunikation.",
    validityMonths: null,
    requiresProof: true,
    fromLms: false,
    iconKey: "Waves",
    color: "text-cyan-700 bg-cyan-50 border-cyan-200",
  },
  // Zertifikate (LMS)
  {
    key: "bls_aed",
    name: "BLS-AED (Basic Life Support)",
    category: "zertifikat",
    level: "basis",
    description: "Reanimations-Basismassnahmen.",
    validityMonths: 24,
    requiresProof: true,
    fromLms: true,
    iconKey: "HeartPulse",
    color: "text-red-700 bg-red-50 border-red-200",
  },
  {
    key: "acls",
    name: "ACLS (Advanced Cardiac Life Support)",
    category: "zertifikat",
    level: "erweitert",
    description: "Erweiterte Reanimation.",
    validityMonths: 24,
    requiresProof: true,
    fromLms: true,
    iconKey: "HeartPulse",
    color: "text-red-700 bg-red-50 border-red-200",
  },
  {
    key: "erste_hilfe",
    name: "Erste-Hilfe",
    category: "zertifikat",
    level: "basis",
    description: "Erste-Hilfe-Kurs.",
    validityMonths: 48,
    requiresProof: true,
    fromLms: true,
    iconKey: "Plus",
    color: "text-red-700 bg-red-50 border-red-200",
  },
  {
    key: "brandschutz",
    name: "Brandschutz",
    category: "zertifikat",
    level: "basis",
    description: "Brandschutz-Unterweisung.",
    validityMonths: 12,
    requiresProof: true,
    fromLms: true,
    iconKey: "Flame",
    color: "text-orange-700 bg-orange-50 border-orange-200",
  },
  {
    key: "datenschutz",
    name: "Datenschutz (DSGVO)",
    category: "zertifikat",
    level: "basis",
    description: "Datenschutz-Unterweisung DSGVO.",
    validityMonths: 12,
    requiresProof: true,
    fromLms: true,
    iconKey: "Lock",
    color: "text-gray-700 bg-gray-50 border-gray-200",
  },
  // Rollen
  {
    key: "schichtleitung",
    name: "Schichtleitung",
    category: "rolle",
    level: "erweitert",
    description: "Schichtverantwortliche:r.",
    validityMonths: null,
    requiresProof: false,
    fromLms: false,
    iconKey: "UserCog",
    color: "text-indigo-700 bg-indigo-50 border-indigo-200",
  },
  {
    key: "pdl",
    name: "PDL — Pflegedienstleitung",
    category: "rolle",
    level: "expert",
    description: "Pflegedienstleitung.",
    validityMonths: null,
    requiresProof: true,
    fromLms: false,
    iconKey: "Crown",
    color: "text-indigo-900 bg-indigo-50 border-indigo-300",
  },
  {
    key: "stellv_pdl",
    name: "Stellv. PDL",
    category: "rolle",
    level: "expert",
    description: "Stellvertretende Pflegedienstleitung.",
    validityMonths: null,
    requiresProof: true,
    fromLms: false,
    iconKey: "Crown",
    color: "text-indigo-800 bg-indigo-50 border-indigo-200",
  },
  {
    key: "wbl",
    name: "WBL — Wohnbereichsleitung",
    category: "rolle",
    level: "erweitert",
    description: "Wohnbereichsleitung.",
    validityMonths: null,
    requiresProof: false,
    fromLms: false,
    iconKey: "Users",
    color: "text-indigo-700 bg-indigo-50 border-indigo-200",
  },
  {
    key: "praxisanleiter",
    name: "Praxisanleiter:in",
    category: "rolle",
    level: "erweitert",
    description: "Praxisanleitung fuer Auszubildende.",
    validityMonths: null,
    requiresProof: true,
    fromLms: false,
    iconKey: "BookOpen",
    color: "text-teal-700 bg-teal-50 border-teal-200",
  },
  {
    key: "teamleitung",
    name: "Teamleitung",
    category: "rolle",
    level: "erweitert",
    description: "Teamleitungs-Funktion.",
    validityMonths: null,
    requiresProof: false,
    fromLms: false,
    iconKey: "Users",
    color: "text-indigo-700 bg-indigo-50 border-indigo-200",
  },
  {
    key: "notfall_sani",
    name: "Notfallsanitaeter:in",
    category: "qualifikation",
    level: "expert",
    description: "NotSan-Ausbildung.",
    validityMonths: null,
    requiresProof: true,
    fromLms: false,
    iconKey: "Siren",
    color: "text-red-700 bg-red-50 border-red-200",
  },
  {
    key: "wkp_aromapflege",
    name: "Aromapflege",
    category: "weiterbildung",
    level: "basis",
    description: "Aroma- und komplementaere Pflege.",
    validityMonths: null,
    requiresProof: true,
    fromLms: false,
    iconKey: "Leaf",
    color: "text-emerald-700 bg-emerald-50 border-emerald-200",
  },
  {
    key: "validation",
    name: "Validation nach Naomi Feil",
    category: "weiterbildung",
    level: "erweitert",
    description: "Kommunikation mit Demenzkranken.",
    validityMonths: null,
    requiresProof: true,
    fromLms: false,
    iconKey: "MessageCircle",
    color: "text-purple-700 bg-purple-50 border-purple-200",
  },
  {
    key: "tracheostoma",
    name: "Tracheostoma-Pflege",
    category: "weiterbildung",
    level: "erweitert",
    description: "Spezielle Atemwegs-Pflege.",
    validityMonths: 24,
    requiresProof: true,
    fromLms: false,
    iconKey: "Wind",
    color: "text-cyan-700 bg-cyan-50 border-cyan-200",
  },
  {
    key: "peg_sonde",
    name: "PEG-Sonden-Pflege",
    category: "weiterbildung",
    level: "basis",
    description: "Enterale Ernaehrung.",
    validityMonths: 24,
    requiresProof: true,
    fromLms: false,
    iconKey: "Droplet",
    color: "text-amber-700 bg-amber-50 border-amber-200",
  },
  {
    key: "diabetes_bt",
    name: "Diabetes-Beraterin",
    category: "weiterbildung",
    level: "erweitert",
    description: "Diabetes mellitus — Beratung und Schulung.",
    validityMonths: 36,
    requiresProof: true,
    fromLms: false,
    iconKey: "Syringe",
    color: "text-rose-700 bg-rose-50 border-rose-200",
  },
  {
    key: "dekubitus",
    name: "Dekubitusprophylaxe Expert:in",
    category: "expertise",
    level: "erweitert",
    description: "Strukturierte Dekubitusprophylaxe.",
    validityMonths: 24,
    requiresProof: true,
    fromLms: false,
    iconKey: "ShieldCheck",
    color: "text-rose-700 bg-rose-50 border-rose-200",
  },
  {
    key: "fbl",
    name: "FBL — Fortbildungs-Leiter:in",
    category: "rolle",
    level: "erweitert",
    description: "Verantwortung fuer interne Fortbildung.",
    validityMonths: null,
    requiresProof: false,
    fromLms: false,
    iconKey: "Presentation",
    color: "text-teal-700 bg-teal-50 border-teal-200",
  },
];

export function getBadgeDef(key: string): BadgeDef | undefined {
  return BADGE_CATALOG.find((b) => b.key === key);
}

export function recommendedForRole(role: string): BadgeDef[] {
  const r = role.toLowerCase();
  if (r === "pdl" || r === "admin") {
    return BADGE_CATALOG.filter((b) =>
      ["pdl", "qm_beauftragt", "hygiene_beauftragt", "arzneimittel_beauftragt", "datenschutz"].includes(b.key),
    );
  }
  if (r === "pflegekraft") {
    return BADGE_CATALOG.filter((b) =>
      ["dgkp", "pfa", "bls_aed", "erste_hilfe", "datenschutz", "brandschutz", "kinaesthetik"].includes(b.key),
    );
  }
  return BADGE_CATALOG.filter((b) => ["datenschutz", "brandschutz"].includes(b.key));
}
